include: package:very_good_analysis/analysis_options.6.0.0.yaml
analyzer:
  exclude: [build/**, lib/**.freezed.dart, lib/**.g.dart]
  enable-experiment:
    - macros
linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    prefer_const_literals_to_create_immutables: false
    prefer_const_constructors: false
