name: spotspeak_mobile
description: Aplikacja SpotSpeak tworzona w ramach pracy inżynierskiej w latach 2024-2025
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  injectable: ^2.4.4

dev_dependencies:
  build_runner: ^2.4.12
  injectable_generator: ^2.6.2
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
