name: spotspeak_mobile
description: Aplikacja SpotSpeak tworzona w ramach pracy inżynierskiej w latach 2024-2025
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  auto_route: ^9.2.2
  bloc: ^8.1.4
  dio: ^5.7.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_db_store: ^5.1.1
  firebase_core: ^3.5.0
  firebase_messaging: ^15.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_map: ^7.0.2
  flutter_map_cancellable_tile_provider: ^3.0.2
  geolocator: ^13.0.1
  get_it: ^7.7.0
  injectable: ^2.4.4
  package_info_plus: ^8.0.2
  path_provider: ^2.1.4
  pretty_dio_logger: ^1.4.0
  sqlite3_flutter_libs: ^0.5.24
  theme_tailor_annotation: ^3.0.1
  url_launcher: ^6.3.0

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.12
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2
  theme_tailor: ^3.0.1
  very_good_analysis: ^6.0.0


flutter:
  uses-material-design: true
  generate: true
