name: spotspeak_mobile
description: Aplikacja SpotSpeak tworzona w ramach pracy inżynierskiej w latach 2024-2025
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  auto_route: ^9.2.2
  auto_size_text: ^3.0.0
  bloc: ^8.1.4
  cached_network_image: ^3.4.1
  cached_video_player_plus: ^3.0.3
  dateable: ^4.0.1
  dio: ^5.7.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_db_store: ^5.1.1
  dio_http2_adapter: ^2.5.3
  easy_debounce: ^2.0.3
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.5
  flutter:
    sdk: flutter
  flutter_appauth: ^8.0.1
  flutter_bloc: ^8.1.6
  flutter_map: ^7.0.2
  flutter_map_animations: ^0.8.0
  flutter_map_cache: ^1.5.1
  flutter_map_cancellable_tile_provider: ^3.0.2
  flutter_map_location_marker: ^9.1.1
  flutter_map_marker_cluster: ^1.4.0
  flutter_map_polywidget: ^1.1.0-dev.7
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.16
  fluttertoast: ^8.2.8
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  geolocator: ^13.0.2
  get_it: ^8.0.2
  get_thumbnail_video: ^0.7.3
  http_parser: ^4.0.2
  image_picker: ^1.1.2
  injectable: ^2.5.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  latlong2: ^0.9.1
  linear_progress_bar: ^1.1.2
  logger: ^2.5.0
  mime: ^2.0.0
  mutex: ^3.1.0
  package_info_plus: ^8.1.1
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.1
  rxdart: ^0.28.0
  sliding_up_panel: ^2.0.0+1
  sqlite3_flutter_libs: ^0.5.27
  url_launcher: ^6.3.1

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  injectable_generator: ^2.6.2
  json_serializable: ^6.9.0
  retrofit_generator: ^9.1.5
  very_good_analysis: ^6.0.0


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/trace_icons_hidden/
    - assets/trace_icons_discovered/
  fonts:
    - family: Inconsolata
      fonts:
        - asset: assets/fonts/inconsolata/Inconsolata-Regular.ttf
        - asset: assets/fonts/inconsolata/Inconsolata-Bold.ttf
          weight: 700
