name: spotspeak_mobile
description: Aplikacja SpotSpeak tworzona w ramach pracy inżynierskiej w latach 2024-2025
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  auto_route: ^9.2.2
  bloc: ^8.1.4
  dio: ^5.7.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_db_store: ^5.1.1
  easy_debounce: ^2.0.3
  firebase_core: ^3.5.0
  firebase_messaging: ^15.1.2
  flutter:
    sdk: flutter
  flutter_appauth: ^7.0.1
  flutter_bloc: ^8.1.6
  flutter_map: ^7.0.2
  flutter_map_animations: ^0.7.1
  flutter_map_cancellable_tile_provider: ^3.0.2
  flutter_secure_storage: ^4.2.1
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  geolocator: ^13.0.1
  get_it: ^7.7.0
  injectable: ^2.4.4
  json_annotation: ^4.9.0
  latlong2: ^0.9.1
  package_info_plus: ^8.0.2
  path_provider: ^2.1.4
  pretty_dio_logger: ^1.4.0
  rxdart: ^0.28.0
  sliding_up_panel: ^2.0.0+1
  sqlite3_flutter_libs: ^0.5.24
  url_launcher: ^6.3.0

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.12
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0
  very_good_analysis: ^6.0.0


flutter:
  uses-material-design: true
  generate: true
  assets:
    - path: assets/
  fonts:
    - family: Inconsolata
      fonts:
        - asset: assets/fonts/inconsolata/Inconsolata-Regular.ttf
        - asset: assets/fonts/inconsolata/Inconsolata-Bold.ttf
          weight: 700
