name: spotspeak_mobile
description: Aplikacja SpotSpeak tworzona w ramach pracy inżynierskiej w latach 2024-2025
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6

dev_dependencies:
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
